type                = "directrequest"
schemaVersion       = 1
evmChainID          = 5
name                = "SSV matcher"
contractAddress     = "0xCC79157eb46F5624204f47AB42b3906cAA40eaB7"

observationSource   = """
    ds          [type="http" method=GET url="http://127.0.0.1:8000?poolId=1"]
    ds_parse    [type="jsonparse" path="poolId"]

    ds -> ds_parse
"""