version: '3.5'

services:
  node:
    container_name: chainlink-node
    image: smartcontract/chainlink:1.10.0
    entrypoint: /bin/sh -c "chainlink node start -d -p /run/secrets/node_password -a /run/secrets/apicredentials"
    restart: always
    environment:
      - ETH_CHAIN_ID
      - LOG_LEVEL=info
      - ROOT
      - ETH_URL
      - MIN_OUTGOING_CONFIRMATIONS
      - MIN_INCOMING_CONFIRMATIONS
      - MINIMUM_CONTRACT_PAYMENT_LINK_JUELS
      - DEFAULT_HTTP_TIMEOUT
      - CHAINLINK_DEV
      - SECURE_COOKIES
      - CHAINLINK_TLS_PORT
      - DATABASE_URL=postgresql://postgres:$CHAINLINK_PGPASSWORD@node-db:5432/$CHAINLINK_DB_NAME?sslmode=disable
    env_file:
      - .env
    ports:
      - 6688:6688
    secrets:
      - node_password
      - apicredentials
      - keystore
    depends_on:
      - node-db

  node-db:
    container_name: chainlink-db
    image: postgres:11.6
    volumes:
      - node-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $CHAINLINK_DB_NAME
      POSTGRES_PASSWORD: $CHAINLINK_PGPASSWORD

secrets:
  node_password:
    file: ./secrets/password.txt
  apicredentials:
    file: ./secrets/apicredentials

volumes:
  node-db-data: