name: Pull request

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build helpers
        run: npm run build --workspace @casimir/helpers

      - name: Build landing app
        run: npm run build --workspace @casimir/landing
        env:
          PUBLIC_STAGE: ${{ env.STAGE }}

      - name: Build users service
        run: npm run build --workspace @casimir/users

      - name: Test cdk stacks
        run: npm run test --workspace @casimir/cdk