name: Pull request

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install and build all package dependencies
        run: npm ci
        env:
          PUBLIC_STAGE: ${{ env.STAGE }}

      - name: Test cdk stacks
        run: npm run test --workspace @casimir/cdk