name: Pull request

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build common lib
        run: npm run build
        working-directory: common/lib

      - name: Build website app
        run: npm run build
        working-directory: apps/website
        env:
          PUBLIC_STAGE: ${{ env.STAGE }}

      - name: Build users service
        run: npm run build
        working-directory: services/users

      - name: Test cdk stacks
        run: |
          npm run test
        working-directory: infrastructure/cdk